### ISSUE TITLE
Optional output compression

### ISSUE THREAD

**Issue by berto-dev** [markcellus/html-express-js#42]
Hello devs! You are part of my stack and i see different parts of the code... so...

I had some problems with the original minification of code and, to be honest, i don't understand why is natively present.

So, i make a local variant and it work, i try to explain this easy mod:

ADD a simple option for easy minify output:
server.set( 'view minify', false )

MOD in [... src/index.js line 24](https://github.com/markcellus/html-express-js/blob/087deb1f2568751368713605dcc12938c3ab322b/src/index.js#L24) with this line:
```
  return data.settings['view minify']===true ? html.replace(/(?<!<pre>|\`)>(\s*)</g, '><').replace(/\n|\r|\/\*[\s\S]*?\*\/|(^|[^:])\/\/.*/g, '').replace(/[\n\r]/g, '').replace(/<(\w+)([^>]*)="([^"\s]+)"([^>]*)>/g, '<$1$2=$3$4>')  : html

```
result:
```ts
async function renderHtmlFileTemplate(path, data, state) {
  const { view } = await import(path);
  const rendered = view(data, state);
  let html = '';
  for (let chunk of rendered) {
    html += chunk;
  }
  return data.settings['view minify']===true ? html.replace(/(?<!<pre>|\`)>(\s*)</g, '><').replace(/\n|\r|\/\*[\s\S]*?\*\/|(^|[^:])\/\/.*/g, '').replace(/[\n\r]/g, '') : html
}
```

REMOVE IN [... src/index.js line 65](https://github.com/markcellus/html-express-js/blob/087deb1f2568751368713605dcc12938c3ab322b/src/index.js#L65C15-L65C15):
```ts
  const html = rawHtml.replace(/[\n\r]/g, ''); <== why this replacer is here without a choose? it doesn't have a sense and can be generate fail during processing or horrible compression
```
result:
```ts
export function html(strings, ...data) {
  let rawHtml = '';
  for (let [i, str] of strings.entries()) {
    const exp = data[i] || '';
    rawHtml += str + exp;
  }
  const html = rawHtml;
  return html;
}
```

Now, if you want to have a "plain code, a soft minification" you can, but if have other necessity, you can approact in other way.

Do you work on this? Can i help on it? if yes, how?

**Comment by berto-dev** [comment]
simple adjustments

**Comment by berto-dev** [comment]
Note apart...
it seems that the regex for comments is more stable when split into parts:
```
return data.settings['view minify']===true ?
html
 .replace(/<!--[\s\S]*?-->/g,'')         //html comments
 .replace( /\/\*[\s\S]*?\*\//g, '')      //css comments
 .replace( /[^:\/]\/\/.*/g, '')          //js comments
 .replace(/(?<!<pre>|\`)>(\s*)</g, '><') // once line code
 .replace(/[\n\r]/g, '')                 // remove multi lines
 .replace(/<(\w+)([^>]*)="([^"\s]+)"([^>]*)>/g, '<$1$2=$3$4>')  // clean html attr 
 : html
 
```

and if you want, suggest to me somethings....

**Comment by markcellus** [comment]
Hey, thanks for the issue. Anyone can contribute to the codebase by opening a PR. You'd have to open one so I can see exactly what's being proposed and the reason for the change. I'm not quite sure if there's anything else I can do here. But please feel free to reopen if there's a specific question, issue, or if there is something I can help with.
